/*
* Consumer Data Standards
* Sample Data Holder to Demonstrate the Consumer Data Right APIs
*
* NOTE: This class is auto generated by the cds-codegen package
* https://github.com/ConsumerDataStandardsAustralia/cds-codegen
* Do not edit the class manually.
*/
package au.org.consumerdatastandards.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;
import java.net.URI;
import java.lang.reflect.Field;
import java.util.List;
import java.math.BigDecimal;

/**
* BankingProductLendingRate
*/
public class BankingProductLendingRate  {
            // The type of rate (fixed, variable, etc). See the next
    // section for an overview of valid values and their meaning
        @SerializedName("lendingRateType")
    private LendingRateType lendingRateType;
            // The rate to be applied
        @SerializedName("rate")
    private String rate;
            // A comparison rate equivalent for this rate
        @SerializedName("comparisonRate")
    private String comparisonRate;
            // The period after which the rate is applied to the balance to
    // calculate the amount due for the period. Calculation of the
    // amount is often daily (as balances may change) but
    // accumulated until the total amount is 'applied' to the
    // account (see applicationFrequency). Formatted according to
    // [ISO 8601
    // Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)
        @SerializedName("calculationFrequency")
    private String calculationFrequency;
            // The period after which the calculated amount(s) (see
    // calculationFrequency) are 'applied' (i.e. debited or
    // credited) to the account. Formatted according to [ISO 8601
    // Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)
        @SerializedName("applicationFrequency")
    private String applicationFrequency;
            // When loan payments are due to be paid within each period.
    // The investment benefit of earlier payments affect the rate
    // that can be offered
        @SerializedName("interestPaymentDue")
    private InterestPaymentDue interestPaymentDue;
            // Rate tiers applicable for this rate
        @SerializedName("tiers")
    private List<BankingProductRateTier> tiers;
            // Generic field containing additional information relevant to
    // the lendingRateType specified. Whether mandatory or not is
    // dependent on the value of lendingRateType
        @SerializedName("additionalValue")
    private String additionalValue;
            // Display text providing more information on the rate.
        @SerializedName("additionalInfo")
    private String additionalInfo;
            // Link to a web page with more information on this rate
        @SerializedName("additionalInfoUri")
    private URI additionalInfoUri;

        
    @ApiModelProperty(value = "The type of rate (fixed, variable, etc). See the next section for an overview of valid values and their meaning", required = true)
    public LendingRateType getLendingRateType() {
        return lendingRateType;
    }

    public void setLendingRateType(LendingRateType lendingRateType) {
        this.lendingRateType = lendingRateType;
    }
    
    public BankingProductLendingRate lendingRateType(LendingRateType lendingRateType) {
        this.lendingRateType = lendingRateType;
        return this;
    }
    
        
    @ApiModelProperty(value = "The rate to be applied", required = true)
    public String getRate() {
        return rate;
    }

    public void setRate(String rate) {
        this.rate = rate;
    }
    
    public BankingProductLendingRate rate(String rate) {
        this.rate = rate;
        return this;
    }
    
        
    @ApiModelProperty(value = "A comparison rate equivalent for this rate", required = false)
    public String getComparisonRate() {
        return comparisonRate;
    }

    public void setComparisonRate(String comparisonRate) {
        this.comparisonRate = comparisonRate;
    }
    
    public BankingProductLendingRate comparisonRate(String comparisonRate) {
        this.comparisonRate = comparisonRate;
        return this;
    }
    
        
    @ApiModelProperty(value = "The period after which the rate is applied to the balance to calculate the amount due for the period. Calculation of the amount is often daily (as balances may change) but accumulated until the total amount is 'applied' to the account (see applicationFrequency). Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)", required = false)
    public String getCalculationFrequency() {
        return calculationFrequency;
    }

    public void setCalculationFrequency(String calculationFrequency) {
        this.calculationFrequency = calculationFrequency;
    }
    
    public BankingProductLendingRate calculationFrequency(String calculationFrequency) {
        this.calculationFrequency = calculationFrequency;
        return this;
    }
    
        
    @ApiModelProperty(value = "The period after which the calculated amount(s) (see calculationFrequency) are 'applied' (i.e. debited or credited) to the account. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)", required = false)
    public String getApplicationFrequency() {
        return applicationFrequency;
    }

    public void setApplicationFrequency(String applicationFrequency) {
        this.applicationFrequency = applicationFrequency;
    }
    
    public BankingProductLendingRate applicationFrequency(String applicationFrequency) {
        this.applicationFrequency = applicationFrequency;
        return this;
    }
    
        
    @ApiModelProperty(value = "When loan payments are due to be paid within each period. The investment benefit of earlier payments affect the rate that can be offered", required = false)
    public InterestPaymentDue getInterestPaymentDue() {
        return interestPaymentDue;
    }

    public void setInterestPaymentDue(InterestPaymentDue interestPaymentDue) {
        this.interestPaymentDue = interestPaymentDue;
    }
    
    public BankingProductLendingRate interestPaymentDue(InterestPaymentDue interestPaymentDue) {
        this.interestPaymentDue = interestPaymentDue;
        return this;
    }
    
        
    @ApiModelProperty(value = "Rate tiers applicable for this rate", required = false)
    public List<BankingProductRateTier> getTiers() {
        return tiers;
    }

    public void setTiers(List<BankingProductRateTier> tiers) {
        this.tiers = tiers;
    }
    
    public BankingProductLendingRate tiers(List<BankingProductRateTier> tiers) {
        this.tiers = tiers;
        return this;
    }
    
        
    @ApiModelProperty(value = "Generic field containing additional information relevant to the lendingRateType specified. Whether mandatory or not is dependent on the value of lendingRateType", required = false)
    public String getAdditionalValue() {
        return additionalValue;
    }

    public void setAdditionalValue(String additionalValue) {
        this.additionalValue = additionalValue;
    }
    
    public BankingProductLendingRate additionalValue(String additionalValue) {
        this.additionalValue = additionalValue;
        return this;
    }
    
        
    @ApiModelProperty(value = "Display text providing more information on the rate.", required = false)
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }
    
    public BankingProductLendingRate additionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
        return this;
    }
    
        
    @ApiModelProperty(value = "Link to a web page with more information on this rate", required = false)
    public URI getAdditionalInfoUri() {
        return additionalInfoUri;
    }

    public void setAdditionalInfoUri(URI additionalInfoUri) {
        this.additionalInfoUri = additionalInfoUri;
    }
    
    public BankingProductLendingRate additionalInfoUri(URI additionalInfoUri) {
        this.additionalInfoUri = additionalInfoUri;
        return this;
    }
    

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        
                BankingProductLendingRate inputModel = (BankingProductLendingRate) o;
        if(! (lendingRateType.equals(inputModel.getLendingRateType()))) { return false; }
        if(! (rate.equals(inputModel.getRate()))) { return false; }
        if(! (comparisonRate.equals(inputModel.getComparisonRate()))) { return false; }
        if(! (calculationFrequency.equals(inputModel.getCalculationFrequency()))) { return false; }
        if(! (applicationFrequency.equals(inputModel.getApplicationFrequency()))) { return false; }
        if(! (interestPaymentDue.equals(inputModel.getInterestPaymentDue()))) { return false; }
        if(! (tiers.equals(inputModel.getTiers()))) { return false; }
        if(! (additionalValue.equals(inputModel.getAdditionalValue()))) { return false; }
        if(! (additionalInfo.equals(inputModel.getAdditionalInfo()))) { return false; }
        if(! (additionalInfoUri.equals(inputModel.getAdditionalInfoUri()))) { return false; }
        return true;
    }

    @Override
    public int hashCode() {
      return Objects.hash(additionalInfoUri,additionalInfoUri,additionalInfoUri,additionalInfoUri,additionalInfoUri,additionalInfoUri,additionalInfoUri,additionalInfoUri,additionalInfoUri,additionalInfoUri);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("class %s {\n", getClass()));        
                        sb.append("    lendingRateType: ").append(toIndentedString(lendingRateType)).append("\n");
                        sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
                        sb.append("    comparisonRate: ").append(toIndentedString(comparisonRate)).append("\n");
                        sb.append("    calculationFrequency: ").append(toIndentedString(calculationFrequency)).append("\n");
                        sb.append("    applicationFrequency: ").append(toIndentedString(applicationFrequency)).append("\n");
                        sb.append("    interestPaymentDue: ").append(toIndentedString(interestPaymentDue)).append("\n");
                        sb.append("    tiers: ").append(toIndentedString(tiers)).append("\n");
                        sb.append("    additionalValue: ").append(toIndentedString(additionalValue)).append("\n");
                        sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
                        sb.append("    additionalInfoUri: ").append(toIndentedString(additionalInfoUri)).append("\n");
                sb.append("}");
        return sb.toString();
    }
    
    private String toIndentedString(java.lang.Object o) {
      if (o == null) {
        return "null";
      }
      return o.toString().replace("\n", "\n    ");
    }
}
