/*
* Consumer Data Standards
* Sample Data Holder to Demonstrate the Consumer Data Right APIs
*
* NOTE: This class is auto generated by the cds-codegen package
* https://github.com/ConsumerDataStandardsAustralia/cds-codegen
* Do not edit the class manually.
*/
package au.org.consumerdatastandards.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;
import java.net.URI;
import java.lang.reflect.Field;
import java.util.List;
import java.math.BigDecimal;

/**
* LinksPaginated
*/
public class LinksPaginated  {
            // Fully qualified link to this API call
        @SerializedName("self")
    private URI self;
            // URI to the first page of this set. Mandatory if this
    // response is not the first page
        @SerializedName("first")
    private URI first;
            // URI to the previous page of this set. Mandatory if this
    // response is not the first page
        @SerializedName("prev")
    private URI prev;
            // URI to the next page of this set. Mandatory if this response
    // is not the last page
        @SerializedName("next")
    private URI next;
            // URI to the last page of this set. Mandatory if this response
    // is not the last page
        @SerializedName("last")
    private URI last;

        
    @ApiModelProperty(value = "Fully qualified link to this API call", required = true)
    public URI getSelf() {
        return self;
    }

    public void setSelf(URI self) {
        this.self = self;
    }
    
    public LinksPaginated self(URI self) {
        this.self = self;
        return this;
    }
    
        
    @ApiModelProperty(value = "URI to the first page of this set. Mandatory if this response is not the first page", required = false)
    public URI getFirst() {
        return first;
    }

    public void setFirst(URI first) {
        this.first = first;
    }
    
    public LinksPaginated first(URI first) {
        this.first = first;
        return this;
    }
    
        
    @ApiModelProperty(value = "URI to the previous page of this set. Mandatory if this response is not the first page", required = false)
    public URI getPrev() {
        return prev;
    }

    public void setPrev(URI prev) {
        this.prev = prev;
    }
    
    public LinksPaginated prev(URI prev) {
        this.prev = prev;
        return this;
    }
    
        
    @ApiModelProperty(value = "URI to the next page of this set. Mandatory if this response is not the last page", required = false)
    public URI getNext() {
        return next;
    }

    public void setNext(URI next) {
        this.next = next;
    }
    
    public LinksPaginated next(URI next) {
        this.next = next;
        return this;
    }
    
        
    @ApiModelProperty(value = "URI to the last page of this set. Mandatory if this response is not the last page", required = false)
    public URI getLast() {
        return last;
    }

    public void setLast(URI last) {
        this.last = last;
    }
    
    public LinksPaginated last(URI last) {
        this.last = last;
        return this;
    }
    

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        
                LinksPaginated inputModel = (LinksPaginated) o;
        if(! (self.equals(inputModel.getSelf()))) { return false; }
        if(! (first.equals(inputModel.getFirst()))) { return false; }
        if(! (prev.equals(inputModel.getPrev()))) { return false; }
        if(! (next.equals(inputModel.getNext()))) { return false; }
        if(! (last.equals(inputModel.getLast()))) { return false; }
        return true;
    }

    @Override
    public int hashCode() {
      return Objects.hash(last,last,last,last,last);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("class %s {\n", getClass()));        
                        sb.append("    self: ").append(toIndentedString(self)).append("\n");
                        sb.append("    first: ").append(toIndentedString(first)).append("\n");
                        sb.append("    prev: ").append(toIndentedString(prev)).append("\n");
                        sb.append("    next: ").append(toIndentedString(next)).append("\n");
                        sb.append("    last: ").append(toIndentedString(last)).append("\n");
                sb.append("}");
        return sb.toString();
    }
    
    private String toIndentedString(java.lang.Object o) {
      if (o == null) {
        return "null";
      }
      return o.toString().replace("\n", "\n    ");
    }
}
