/*
* Consumer Data Standards
* Sample Data Holder to Demonstrate the Consumer Data Right APIs
*
* NOTE: This class is auto generated by the cds-codegen package
* https://github.com/ConsumerDataStandardsAustralia/cds-codegen
* Do not edit the class manually.
*/
package au.org.consumerdatastandards.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
* UnitOfMeasure
* 
* * The unit of measure that applies to the tierValueMinimum and
* tierValueMaximum values e.g. 'DOLLAR', 'MONTH' (in the case
* of term deposit tiers), 'PERCENT' (in the case of
* loan-to-value ratio or LVR)
* */
@JsonAdapter(UnitOfMeasure.Adapter.class)
public enum UnitOfMeasure {
        DOLLAR("DOLLAR"),        PERCENT("PERCENT"),        MONTH("MONTH"),        DAY("DAY");    
    private String value;
    
    UnitOfMeasure(String value) {
      this.value = value;
    }
    
    @Override
    public String toString() {
      return String.valueOf(value);
    }
    
    public String getValue() {
        return value;
    }

    public static UnitOfMeasure fromValue(String value) {
      for (UnitOfMeasure b : UnitOfMeasure.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
    
    public static class Adapter extends TypeAdapter<UnitOfMeasure> {
        @Override
        public void write(final JsonWriter jsonWriter, final UnitOfMeasure enumeration) throws IOException {
          jsonWriter.value(enumeration.getValue());
        }
        
        @Override
        public UnitOfMeasure read(final JsonReader jsonReader) throws IOException {
          String value = jsonReader.nextString();
          return UnitOfMeasure.fromValue(value);
        }
    }
}
