/*
 * Consumer Data Standards
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of rate (base, bonus, etc). See the next section for an overview of valid values and their meaning
 */
@JsonAdapter(DepositRateType.Adapter.class)
public enum DepositRateType {
  
  BONUS("BONUS"),
  
  BUNDLE_BONUS("BUNDLE_BONUS"),
  
  FIXED("FIXED"),
  
  FLOATING("FLOATING"),
  
  INTRODUCTORY("INTRODUCTORY"),
  
  MARKET_LINKED("MARKET_LINKED"),
  
  VARIABLE("VARIABLE");

  private String value;

  DepositRateType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DepositRateType fromValue(String text) {
    for (DepositRateType b : DepositRateType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DepositRateType> {
    @Override
    public void write(final JsonWriter jsonWriter, final DepositRateType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DepositRateType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DepositRateType.fromValue(String.valueOf(value));
    }
  }
}

